language: node_js
node_js:
- '6'
env:
  matrix:
  - TRAVIS_NODE_VERSION="6.3"
install:
- npm install
cache:
  directories:
  - node_modules
deploy:
  provider: elasticbeanstalk
  access_key_id: AKIAIPKLFWX5TZYVHIFA
  secret_access_key:
    secure: ep9Ar2Bgcgp0dVR+ujuPAPGkVMK2MB01fRuZmNKkod3or0Ouivq8vU/FcujA2M8J0iHglmF2y7isWLNHPtcKljUtae+uTuZ8aNkNQENjw7EtOTEprj1UGu2bAKbV04tnV3sTj9MgVq9+kpx144hOhHbeg06A7UbSm60x3DKHi3rp0m8LkoU9YtUg/o5PcRqQrEfRMkiYg1iD6adi+wcZmNOBTK7hp5pdNaxAWmvFRDyjDSAlgh2/HImhevDpNQxSSrLDpfKA42aFMWrXNEuie/jMjTDb8b9pgXZCKHgEhzGgPisyY2qmd/cSqd7Pb+0a1ffoz0i12Y5u2zwTeaeNufWokxNbn9NQ1fTGPpj/0EJDhKWEICj21ucjIM0fSDtdmXzJk7JsZtd+buKLf8cWKgDL0EiYn/BftCBDtKyzwGHmEXwI2qkENctWTrf8mFCchqWK8Iygfu9vJr7HLoC58BqaKitiGS/0amBeDWNJ9unTTAnM71Y1UKCxiVO5FSukE6i/TKWy4jn7ICSETC+Pjngf9R7pVtBTYW0KSNdQWWVhKho8DjmeNJewKrV4Bi8SV1JdUw75FwDylkbNVUe3kChk/HvCx6lKcEDiupSZYsSuCVfsYhCerlT8NJteJhJKSCBI2TcKEMacXmEVcoGh6A4283MTz285gRMUcJ36Cd4=
  region: us-east-2
  app: flickpick
  env: fliq
  bucket_name: elasticbeanstalk-us-east-2-088432678416
  on:
    repo: rcornell/fliq
    branch: dev
